# this script was generated by http://bioforecasts.science.unimelb.edu.au/soil_oz/ on 2024-02-09 04:32:02.562404
# [BP] This is the script used to generate dat/kingsParkSoil.csv
# to run it you need the latest version of R and to install NicheMapR and microclima via devtools using the following code:
# install.packages('devtools')
# devtools::install_github('mrke/NicheMapR')
# library(NicheMapR)
# get.global.climate('put a path here for the global climate dataset')
# devtools::install_github('ilyamaclean/microclima')

library(NicheMapR)

# microclimate simulation
ystart <- 2021
yfinish <- 2022
dstart <- "01/01/2021"
dfinish <- "31/10/2022"
minshade <- 0
maxshade <- 100
Thcond <- 2.5
SpecHeat <- 870
Density <- 2.56
BulkDensity <- 1.3
windfac <- 1
REFL <- 0.2
cap <- 0
SLE <- 0.95
warm <- 0
Usrhyt <- 0.01
clearsky <- 0
lon <- 115.835126
lat <- -31.96282
if(FALSE){
  cat('downloading DEM via package elevatr \n')
  dem <- microclima::get_dem(r = NA, lat = lat, lon = lon, resolution = 30, zmin = -20, xdims = 100, ydims = 100)
  elev <- raster::extract(dem, c(lon, lat))[1]        
  xy <- data.frame(x = lon, y = lat)
  sp::coordinates(xy) = ~x + y
  sp::proj4string(xy) = "+init=epsg:4326"
  xy <- as.data.frame(sp::spTransform(xy, raster::crs(dem)))
  slope <- raster::terrain(dem, unit = "degrees")
  slope <- raster::extract(slope, xy)
  aspect <- raster::terrain(dem, opt = "aspect", unit = "degrees")
  aspect <- raster::extract(aspect, xy)
  ha36 <- 0
  for (i in 0:35) {
    har <- microclima::horizonangle(dem, i * 10, raster::res(dem)[1])
    ha36[i + 1] <- atan(raster::extract(har, xy)) * (180/pi)
  }
  hori <- spline(x = ha36, n = 24, method =  'periodic')$y
  hori[hori < 0] <- 0
  hori[hori > 90] <- 90
}else{
  slope <- 0
  aspect <- 0
  hori<- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
  ha36 <- spline(x = hori, n = 36, method =  'periodic')$y
  ha36[ha36 < 0] <- 0
  ha36[ha36 > 90] <- 90
  elev <- NA
}
soilgrids <- 0
spatial <- NA
ERR <- 1.5
micro <- micro_aust(SLE = SLE, ERR = ERR, Thcond = Thcond, SpecHeat = SpecHeat, ystart = ystart, yfinish = yfinish, Usrhyt = Usrhyt, soilgrids = soilgrids,
                    windfac = windfac, slope = slope, aspect = aspect, REFL = REFL,
                    hori = hori, minshade = minshade,
                    maxshade = maxshade, loc = c(lon, lat), runshade = 0,
                    run.gads = 1, snowmodel = 1, BulkDensity =  BulkDensity, Density = Density,
                    cap = cap, opendap = 1, warm = warm,
                    spatial = spatial, dailywind = dailywind, elev = elev)
while(min(micro$metout[,1]) == 0 & ERR <= 3){
  cat("model crashed, trying a higher error tolerance \n")
  ERR <- ERR + 0.5
  micro <- micro_aust(SLE = SLE, ERR = ERR, Thcond = Thcond, SpecHeat = SpecHeat, ystart = ystart, yfinish = yfinish, Usrhyt = Usrhyt, soilgrids = soilgrids,
                      windfac = windfac, slope = slope, aspect = aspect, REFL = REFL,
                      hori = hori, minshade = minshade,
                      maxshade = maxshade, loc = c(lon, lat), runshade = 0,
                      run.gads = 1, snowmodel = 1, BulkDensity =  BulkDensity, Density = Density,
                      cap = cap, opendap = 1, warm = warm,
                      spatial = spatial, dailywind = dailywind, elev = elev)
}

# plots

cols <- rainbow(10)

soil <- as.data.frame(micro$soil)
metout <- as.data.frame(micro$metout)
tz <- 'Australia/Perth'
dates <- as.POSIXct(as.character(micro$dates), format = "%Y-%m-%d %H:%M:%S", tz = tz)
dates2 <- as.POSIXct(as.character(micro$dates2), format = "%Y-%m-%d", tz = tz)

seas <- 'FALSE'
if(seas){
  dstart <- paste0("01/01/", '2022')
  dfinish <- paste0("30/06/", as.numeric('2022') + 1)
  dates2plot <- seq(as.POSIXct(paste0("01/07/", '2022',"00:00"), format = "%d/%m/%Y %H:%M", tz = tz), as.POSIXct(paste0("30/06/", as.numeric('2022') + 1,"23:00"), format = "%d/%m/%Y %H:%M", tz = tz), 3600)
  dates2plot2 <- seq(as.POSIXct(paste0("01/07/", '2022',"00:00"), format = "%d/%m/%Y %H:%M", tz = tz), as.POSIXct(paste0("30/06/", as.numeric('2022') + 1,"23:00"), format = "%d/%m/%Y %H:%M", tz = tz), 3600 * 24)
  if(as.POSIXct(dfinish, format = "%d/%m/%Y", tz = tz) > Sys.time()){
    dstart <- paste0("01/01/", '2022' - 1)
    dfinish <- paste0("30/06/", as.numeric('2022'))      
    if(as.POSIXct(dfinish, format = "%d/%m/%Y", tz = tz) > Sys.time()){
      dfinish <- format(Sys.time() - 3600 * 24, "%d/%m/%Y", tz = tz)
    }
    dates2plot <- seq(as.POSIXct(paste0("01/07/", as.numeric('2022') - 1,"00:00"), format = "%d/%m/%Y %H:%M", tz = tz), as.POSIXct(paste0(dfinish,"23:00"), format = "%d/%m/%Y %H:%M", tz = tz), 3600)
    dates2plot2 <- seq(as.POSIXct(paste0("01/07/", as.numeric('2022') - 1,"00:00"), format = "%d/%m/%Y %H:%M", tz = tz), as.POSIXct(paste0(dfinish,"23:00"), format = "%d/%m/%Y %H:%M", tz = tz), 3600 * 24)
  }
}else{
  dstart <- paste0("01/07/", as.numeric('2022') - 1)
  dfinish <- paste0("31/12/", '2022')
  if(as.POSIXct(dfinish, format = "%d/%m/%Y") > Sys.time()){
    dfinish <- format(Sys.time() - 3600 * 24, "%d/%m/%Y", tz = tz)
  }
  dates2plot <- seq(as.POSIXct(paste0("01/01/", '2022', "00:00"), format = "%d/%m/%Y %H:%M", tz = tz), as.POSIXct(paste0(dfinish, "23:00"), format = "%d/%m/%Y %H:%M", tz = tz), 3600)
  dates2plot2 <- seq(as.POSIXct(paste0("01/01/", '2022',"00:00"), format = "%d/%m/%Y %H:%M", tz = tz), as.POSIXct(paste0(dfinish, "23:00"), format = "%d/%m/%Y %H:%M", tz = tz), 3600 * 24)
}
dates2plot2 <- as.POSIXct(format(dates2plot2, "%Y-%m-%d"), format = "%Y-%m-%d", tz = tz) # need this to avoid issue with daylight savings

metout$dates2 <- as.POSIXct(format(dates, "%Y/%m/%d"), format = "%Y/%m/%d", tz = tz)
years <- as.numeric(format(dates, "%Y"))
daysinyear <- years
leapyears <- seq(1904, 3000, 4)
daysinyear[years %in% leapyears] <- 366
daysinyear[!years %in% leapyears] <- 365
metout$DOY <- as.numeric(format(dates, "%j"))

months <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
if('all' == "all"){
  day <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", seq(10, 31))
}else{
  day <- 'all'
}
if('all' == "all"){
  subs <- which(dates %in% dates2plot)
  subs2 <- which(format(dates2, "%Y-%m-%d") %in% format(dates2plot2))
}else{
  subs <- which(format(dates, "%B") == 'all' & format(dates, "%d") %in% day & dates %in% dates2plot)
  subs2 <- which(format(dates2, "%B") == 'all' & format(dates2, "%d") %in% day & format(dates2, "%Y-%m-%d") %in% format(dates2plot2))
}

datelab <- ""

# soil temperature plot

dmonths <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
depths <- c("0cm", "2.5cm", "5cm", "10cm", "15cm", "20cm", "30cm", "50cm", "100cm", "200cm")
depths2 <- c("D0cm", "D2.5cm", "D5cm", "D10cm", "D15cm", "D20cm", "D30cm", "D50cm", "D100cm", "D200cm")
depchoice <- which(depths %in% c("0cm", "2.5cm", "5cm", "10cm", "15cm", "20cm"))
depchoice2 <- which(depths2 %in% paste0("D", c("0cm", "2.5cm", "5cm", "10cm", "15cm", "20cm")))
if('all' == "all"){
  subs <- which(dates %in% dates2plot)
  subs2 <- which(dates2 %in% dates2plot2)
}else{
  subs <- which(format(dates, "%B") == 'all' & format(dates, "%d") %in% day & dates %in% dates2plot)
  subs2 <- which(format(dates2, "%B") == 'all' & format(dates2, "%d") %in% day & dates2 %in% dates2plot2)
}

colselect <- depchoice + 2
ymax <- max(soil[subs, colselect])
ymin <- min(soil[subs, colselect])

zens <- metout$ZEN[subs]

# plotting soil temperature for minimum shade
for(i in 1:length(depchoice)){
  if(i == 1){
    plot(dates[subs], soil[subs, depchoice[i] + 2], xlab = "hour of day", ylab = "soil temperature (°C)"
         , col = cols[depchoice[i]], ylim = c(ymin, ymax), type = "l", main = paste0('all', ': ', round(micro$minshade[1], 1), '% shade, ', round(0, 1), '° slope, ', round(0, 1), '° aspect, ', round(0.2, 1), '% albedo, ', round(micro$elev, 0), 'm elev'))
    if('all' != "all" & 'all' != "all"){
      abline(v = dates[subs][which(zens < 90)][1] - 1.5, lty = 2, col = 'grey')
      abline(v = dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, lty = 2, col = 'grey')
      text(dates[subs][which(zens < 90)][1] - 1.5, mean(range(soil[subs, 3:12])), labels = 'sunrise', srt = 90, col = 'grey')
      text(dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, mean(range(soil[subs, 3:12])), labels = 'sunset', col = 'grey', srt = 90)
    }
    if(max(metout[subs, 18]) > 0){
      points(dates[subs], metout[subs, 18], col = 'grey', type = 'h', lty = 1)
      legend(x = dates[subs][1] + 0.05 * (dates[subs][length(subs)] - dates[subs][1]), y = ymax, legend = "snow present, cm", col = 'grey', bty = 'n', lty = 1, lwd = 2)
    }
    points(dates[subs], soil[subs, depchoice[i] + 2], xlab = "hour of day", ylab = "soil temperature (°C)"
           , col = cols[depchoice[i]], ylim = c(ymin, ymax), type = "l")
    axis(side = 4, at = seq(0, 300, 10))
    mtext(side = 4, line = -1, "snow depth, cm")
  }else{
    points(dates[subs], soil[subs, depchoice[i] + 2], col = cols[depchoice[i]], type = "l")
  }
  
}
legend(x = dates[subs][1] - 0.05 * (dates[subs][length(subs)] - dates[subs][1]), y = ymax, legend = depths[depchoice], col = cols[depchoice], bty = 'n', lty = rep(1, length(depchoice)))

# aboveground microclimate plots

with(metout, {plot(TALOC[subs] ~ dates[subs], xlab = "hour of day", cex.lab = 1.2, ylab = "°C"
                   , type = "l", ylim = c(min(TALOC[subs], TAREF[subs]), max(TALOC[subs], TAREF[subs])), main = "air temperature", xaxt = 'n')})
#axis(side = 1, at = seq(0, 24, 3), labels = seq(0, 24, 3))
if('all' != "all" & 'all' != "all"){
  abline(v = dates[subs][which(zens < 90)][1] - 1.5, lty = 2, col = 'grey')
  abline(v = dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, lty = 2, col = 'grey')
  text(dates[subs][which(zens < 90)][1] - 1.5, mean(range(metout$TALOC[subs])), labels = 'sunrise', srt = 90, col = 'grey')
  text(dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, mean(range(metout$TALOC[subs]))-0.5, labels = 'sunset', col = 'grey', srt = 90)
}
with(metout, {points(TAREF[subs] ~ dates[subs], type = "l",lty = 2, col = 'blue')})
with(metout, {plot(RHLOC[subs] ~ dates[subs], xlab = "hour of day", ylab = "%"
                   , type = "l",ylim = c(0, 100), cex.lab = 1.2, main = "humidity")})
legend('top', legend = c("2 m", paste0(0.01, " cm")), col = c('blue', 'black'), lty = c(2, 1), bty = 'n', horiz = FALSE, cex = 0.75)
if('all' != "all" & 'all' != "all"){
  abline(v = dates[subs][which(zens < 90)][1] - 1.5, lty = 2, col = 'grey')
  abline(v = dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, lty = 2, col = 'grey')
  text(dates[subs][which(zens < 90)][1] - 1.5, 50, labels = 'sunrise', srt = 90, col = 'grey')
  text(dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, 50, labels = 'sunset', col = 'grey', srt = 90)
}
with(metout, {points(RH[subs] ~ dates[subs], type = "l", col = 'blue', lty = 2)})
with(metout, {plot(VREF[subs] ~ dates[subs], xlab = "hour of day", cex.lab = 1.2,  ylab = "m/s"
                   , type = "l", main = "wind speed", col = 'blue', lty = 2, ylim = c(0, max(metout$VREF)))})
legend('top', legend = c("2 m", paste0(0.01, " cm")), col = c('blue', 'black'), lty = c(2, 1), bty = 'n', horiz = FALSE, cex = 0.75)
if('all' != "all" & 'all' != "all"){
  abline(v = dates[subs][which(zens < 90)][1] - 1.5, lty = 2, col = 'grey')
  abline(v = dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, lty = 2, col = 'grey')
  text(dates[subs][which(zens < 90)][1] - 1.5, mean(range(metout$VREF[subs])), labels = 'sunrise', srt = 90, col = 'grey')
  text(dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, mean(range(metout$VREF[subs])), labels = 'sunset', col = 'grey', srt = 90)
}
with(metout, {points(VLOC[subs] ~ dates[subs], type = "l")})
with(metout, {plot(SOLR[subs] ~ dates[subs], xlab = "hour of day", ylim = c(0, 1100), cex.lab = 1.2, ylab = "W/m2"
                   , col = 'orange', type = "h", lwd = 2, main = "solar radiation")})
legend('top', legend = c("2 m", paste0(0.01, " cm")), col = c('blue', 'black'), lty = c(2, 1), bty = 'n', horiz = FALSE, cex = 0.75)
if('all' != "all" & 'all' != "all"){
  abline(v = dates[subs][which(zens < 90)][1] - 1.5, lty = 2, col = 'grey')
  abline(v = dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, lty = 2, col = 'grey')
  text(dates[subs][which(zens < 90)][1] - 1.5, mean(range(metout$SOLR[subs])), labels = 'sunrise', srt = 90, col = 'grey')
  text(dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, mean(range(metout$SOLR[subs])), labels = 'sunset', col = 'grey', srt = 90)
}

# soil moisture plot

colselect <- depchoice + 2
ymax <- max(soilmoist[subs, colselect]) * 100
ymin <- min(soilmoist[subs, colselect]) * 100

zens <- metout$ZEN[subs]
dosoilgrids <- FALSE
if(dosoilgrids){
  ov <- jsonlite::fromJSON(paste0('https://rest.soilgrids.org/query?lon=',micro$longlat[1],'&lat=',micro$longlat[2],',&attributes=BLDFIE,SLTPPT,SNDPPT,CLYPPT'), flatten = TRUE)
  soilpro <- cbind(c(0,5,15,30,60,100,200), unlist(ov$properties$BLDFIE$M)/1000, unlist(ov$properties$CLYPPT$M), unlist(ov$properties$SLTPPT$M), unlist(ov$properties$SNDPPT$M) )
  colnames(soilpro) <- c('depth', 'blkdens', 'clay', 'silt', 'sand')
  stypes <- NULL
  for(m in 1:nrow(soilpro)){
    ssq<-(CampNormTbl9_1[, 2] - soilpro[m, 4] / 100) ^ 2 + (CampNormTbl9_1[, 3] - soilpro[m, 3] / 100) ^ 2
    stypes[m] <- which(ssq == min(ssq))
  }
  soils <- as.character(CampNormTbl9_1[, 1])
  profile <- as.data.frame(cbind(soilpro[, 1], soils[stypes]), stringsAsFactors = FALSE)
  profile[, 1] <- as.numeric(profile[, 1])
  profile <- cbind(profile, soilpro[, c(2, 3, 5)])
  profile[, 3] <- round(profile[, 3], 1) # round bulk density to 1 decimal place
  colnames(profile)<-c('depth', 'soiltype', 'blkdens', 'clay', 'sand')
}
# plotting soil moisture for minimum shade
for(i in 1:length(depchoice)){
  if(i == 1){
    plot(dates[subs], soilmoist[subs, depchoice[i] + 2] * 100, xlab = "hour of day", ylab = "soil moisture (%)"
         , col = cols[depchoice[i]], ylim = c(0, ymax), type = "l", main = paste0('all', ': ', round(0, 1), '% shade, ', round(0, 1), '° slope, ', round(0, 1), '° aspect, ', round(0.2, 1), '% albedo, ', round(micro$elev, 0), 'm elev'))
    #axis(side = 1, at = seq(0, 24, 3), labels = seq(0, 24, 3))
    if('all' != "all" & 'all' != "all"){
      abline(v = dates[subs][which(zens < 90)][1] - 1.5, lty = 2, col = 'grey')
      abline(v = dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, lty = 2, col = 'grey')
      text(dates[subs][which(zens < 90)][1] - 1.5, mean(range(soil[subs, 3:12])), labels = 'sunrise', srt = 90, col = 'grey')
      text(dates[subs][which(zens < 90)][length(dates[subs][which(zens < 90)])] - 0.5, mean(range(soil[subs, 3:12])), labels = 'sunset', col = 'grey', srt = 90)
    }
  }else{
    points(dates[subs], soilmoist[subs, depchoice[i] + 2] * 100, col = cols[depchoice[i]], type = "l")
  }
  points(dates2[subs2], micro$RAINFALL[subs2], col = 'grey', type = 'h', lty = 1)
  legend(x = dates[subs][1] + 0.5 * (dates[subs][length(subs)] - dates[subs][1]), y = ymax, legend = "rainfall, mm", col = 'grey', bty = 'n', lty = 1, lwd = 1)
  axis(side = 4, at = seq(0, 100, 5))
  mtext(side = 4, line = -1, "rainfall, mm")
}
if(FALSE){
  addtable2plot(x = dates[subs][round(0.80 * length(dates[subs]))], ymax * 0.75, profile)
}
legend(x = dates[subs][1] - 0.05 * (dates[subs][length(subs)] - dates[subs][1]), y = ymax, legend = depths[depchoice], col = cols[depchoice], bty = 'n', lty = rep(1, length(depchoice)))
