---
title: "PSHB Models"
output: html_document
date: "2023-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic life history

Polyphagous shothole borer, *Euwallacea fornicatus*, is a pest of a wide range of plants and has recently expanded its range from south-east Asia to Africa, the Americas, and Australia.

Mated females alight on a host plant and bore a small gallery in the host tree tissue. They seed an ambrosia fungus into this gallery and spend some amount of time building the gallery before laying eggs.  After hatching juveniles, moult through several larval instars, pupate and eventually eclose as adults.  The sex ratio of adults is m:f 1:3-5. Males are wingless and never leave the gallery.  Females are winged. They mate with their brothers, and then exit the gallery to found a new gallery (on the same or a different host).  The rate of egg laying declines steadily over time, with females eventually dying in the gallery rather than forming a new one.

Development of all stages is strongly temperature dependent.  There is some evidence of developmental deaths occurring between hatching and pupation. Other sources of mortality are likely at the dispersal phase (predation, misadventure), otherwise the life history is fairly safe from predation.  

## Our treatment

### Continuous time model

We construct a continuous time model. We let:

  * $E(t)$ be the number of eggs at time $t$
  * $L(t)$ be the number of all larval and pupal stages at time $t$
  * $P(t)$ be the number of pre-reproductive adult females at time $t$
  * $A(t)$ be the number of reproductive females at time $t$.
  
We measure time in degree.days, so can re-scale our results back to the absolute time axis *post hoc*.

### Within gallery dynamics

With the above population partitions, the life-history suggests the following system of ODEs to describe the within gallery dynamics.

\begin{align}
\frac{\mathrm{d}E}{\mathrm{d}t} &= f(t)A-\alpha_EE, A(0) = 1 \\
\frac{\mathrm{d}L}{\mathrm{d}t} &= \alpha_EE-\alpha_LL - \delta_LL \\
\frac{\mathrm{d}P}{\mathrm{d}t} &= \alpha_LL-\alpha_PP \\
\frac{\mathrm{d}A}{\mathrm{d}t} &= \alpha_PP-\delta_AA \\
\end{align}

where the $\alpha$ parameters control the rate of transition between partitions.  The $\delta$ parameters control the death rate.  $f(t)$ controls fecundity but is itself a function of time, such that fecundity declines with the cumulative number of Larva produced:

$$f(t) = \frac{f_0}{1+c\int_0^t{L \mathrm{d}L}}$$.

This is consistent with both the notion of maternal care consuming the female's resources, but also consistent with a finite reproductive output per female.  $f_0$ is the female's initial rate of egg laying, and $c$ determines the cost per Larva to future reproduction.

### Discrete time model

An alternative modelling strategy is to discretise time into small pieces relative to the time scale of the life history.  We could choose something like a time interval being 480 degree hours (24h @ 20 degrees), for example.

Using the same state variables as above we would have:

\begin{align}
E(t+1) = E(t) + fA(t) - \alpha_EE(t) 
L(t+1) = L(t) + \alpha_EE(t) - \alpah_LL - \delta_LL
P(t+1) = P(t) + \alpah_LL - \alpha_PP
A(t+1) = A(t) + \alpha_PP - \delta_AA
\end{align}

Which can be written in matrix form as,



### Between gallery dynamics

Here, we treat each host tree as a patch of habitat.  We look to describe the number of galleries over time, within a host, $A(t)$.  We let the host have a carrying capacity of galleries



We index patches with $i$.  We now make the number of adult females a function of time and patch, $A(i, t)$.